//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MAVİRESTAURANT.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Galeri
    {
        public int GaleriId { get; set; }
        public Nullable<int> ResimId { get; set; }
    
        public virtual Resim Resim { get; set; }
    }
}
