//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MAVİRESTAURANT.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hakkimizda
    {
        public int Hakkimizda_Id { get; set; }
        public Nullable<int> HakkimizdaResim { get; set; }
        public string Baslik { get; set; }
        public string Paragraf1 { get; set; }
        public string Paragraf2 { get; set; }
        public string Paragraf3 { get; set; }
        public string Paragraf4 { get; set; }
        public string Paragraf5 { get; set; }
        public string Paragraf6 { get; set; }
        public Nullable<bool> Durum { get; set; }
    
        public virtual Resim Resim { get; set; }
    }
}
