//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MAVİRESTAURANT.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class IletisimBilgileri
    {
        public int Iletisimbilgi_Id { get; set; }
        public string Eposta { get; set; }
        public string Adres { get; set; }
        public string Tel { get; set; }
        public string HaritaYolu { get; set; }
    }
}
