//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MAVİRESTAURANT.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class OdemeKosullari
    {
        public int OdemeKosul_Id { get; set; }
        public Nullable<int> KosulResim { get; set; }
        public string KosulBaslik1 { get; set; }
        public string KosulBaslik2 { get; set; }
        public string KosulBaslik3 { get; set; }
        public string KosulParagraf1 { get; set; }
        public string KosulParagraf2 { get; set; }
        public string KosulParagraf3 { get; set; }
        public string KosulParagraf4 { get; set; }
        public string KosulParagraf5 { get; set; }
        public Nullable<bool> KosulDurum { get; set; }
    
        public virtual Resim Resim { get; set; }
    }
}
