//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MAVİRESTAURANT.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class siparis
    {
        public int id { get; set; }
        public string ad { get; set; }
        public string soyad { get; set; }
        public string urunad { get; set; }
        public Nullable<int> adet { get; set; }
        public string fiyat { get; set; }
        public Nullable<System.DateTime> tarih { get; set; }
    }
}
