//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MAVİRESTAURANT.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TeslimatKosullari
    {
        public int Teslimat_Id { get; set; }
        public Nullable<int> TeslimatResim { get; set; }
        public string TeslimatBaslik { get; set; }
        public string TeslimatMetin1 { get; set; }
        public string TeslimatMetin2 { get; set; }
        public string TeslimatMetin3 { get; set; }
        public string TeslimatMetin4 { get; set; }
        public Nullable<bool> MetinDurum { get; set; }
    
        public virtual Resim Resim { get; set; }
    }
}
