//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MAVİRESTAURANT.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Urunler
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Urunler()
        {
            this.CokSatanlar = new HashSet<CokSatanlar>();
        }
    
        public int UrunId { get; set; }
        public string UrunKod { get; set; }
        public Nullable<int> Kategori { get; set; }
        public string UrunAd { get; set; }
        public Nullable<int> Stok { get; set; }
        public Nullable<int> UrunResim { get; set; }
        public string Fiyat { get; set; }
        public string Aciklama { get; set; }
        public Nullable<bool> Durum { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CokSatanlar> CokSatanlar { get; set; }
        public virtual Kategori Kategori1 { get; set; }
        public virtual Resim Resim { get; set; }
    }
}
